### PR TITLE
feat: add thinking animation

### LINKED ISSUE #420: Chatbot thinking animation
Use the lottie file provided by the design team for the loading animation in the chatbot panel

[chatbot-loading.json.zip](https://github.com/refstudio/refstudio/files/12437224/chatbot-loading.json.zip)

### PR DESCRIPTION
**Pull request by sehyod**
This adds a thinking animation for the chatbot
I added `vitest-canvas-mock` because tests trying to render lottie files were crashing otherwise (cf. https://github.com/felippenardi/lottie-react-web/issues/21)

https://github.com/refstudio/refstudio/assets/58954208/ce3376d7-0b08-4b0b-9557-5135db3c1f1c

Closes #420

### CODE REVIEW

**Comment by cguedes** [comment]
@sehyod do you think we can also use this animation for the text editor?

**Comment by sehyod** [comment]
> @sehyod do you think we can also use this animation for the text editor?

Do you mean for the sentence completion? If so, it is possible but trickier because the sentence completion is a prosemirror plugin so it's not React

**Comment by cguedes** [comment]
Yes, there. Ok.

**Review by cguedes — APPROVED** [review]
I'm glad on how easy was to add Lottie 👏

**Pull request merged**
