### PR TITLE
feat: Add python tests script and run python tests in pre-push

### LINKED ISSUE #391: bug: python tests don't run in the git push hook
We should have python tests running in the git push hook.

I've just missed the following failing python test when merging #389.

image

### PR DESCRIPTION
**Pull request by cguedes**
@gjreda I've just noticed that the #389 is failing in the CI after merge agains main!

This PR adds an utility to run python tests from the project root using yarn `yarn python:tests` and updates the git push hook to also run python tests.

@gjreda please fix the error reported in #391 (I don't know how 😅).
_____
fixes #391

### CODE REVIEW

**Comment by gjreda** [comment]
@cguedes The tests started to fail when you pushed this commit to the PR: https://github.com/refstudio/refstudio/pull/389/commits/f0266033ed058e459b68b7b0fbf87e54140b8f58

I'll push a fix, but they were failing before merging into main. The root cause is that you [changed the filename](https://github.com/refstudio/refstudio/pull/389/commits/f0266033ed058e459b68b7b0fbf87e54140b8f58#diff-aecd2e6bb1e4f5c776d51ddd0be8303d9b662d1c71f40648f0106447c6c513fcR14) for projects storage, but did not update the tests.

**Comment by gjreda** [comment]
I suspect the bigger bug here is in your merge process: since we have historically ignored when codecov/patch is failing, I'm going to guess you thought that was the cause of the ❌ on the PR, and not that actual tests were failing.

**Comment by cguedes** [comment]
> I know I've been guilty of this in the past too, so we should probably figure out how to make codecov/patch work as we'd like or simply get rid of it, since we do not trust it.

You are right. I thought it was again the codecov/patch issue.
We need to fix our merge process and get rid of codecov/patch. @sehyod what do you think of this?

**Comment by gjreda** [comment]
fixes #391

**Comment by sehyod** [comment]
> > I know I've been guilty of this in the past too, so we should probably figure out how to make codecov/patch work as we'd like or simply get rid of it, since we do not trust it.
> 
> You are right. I thought it was again the codecov/patch issue. We need to fix our merge process and get rid of codecov/patch. @sehyod what do you think of this?

Yes, I 100% agree! codecov/patch is not super useful anyway, the most important is codecov/project

**Pull request merged**
