### PR TITLE
chore: add ruff for Python linting

### PR DESCRIPTION
**Pull request by gjreda**
- https://github.com/refstudio/refstudio/issues/26

Adding ruff with its default settings as a pre-push hook for now. I imagine we'll want to tweak some settings later (like line length).

Once this is merged, devs will need to run:
```
$ poetry install
```

### CODE REVIEW

**Comment by cguedes** [comment]
@gjreda Does it make sense add package.json scripts for _check_ and _fix_ like we did for eslint and prettier?

You can check https://github.com/refstudio/refstudio/pull/37 for what I've implemented for prettier.

**Review by cguedes — CHANGES_REQUESTED** [review]
@gjreda Does it make sense add package.json scripts for check and fix like we did for eslint and prettier?

You can check https://github.com/refstudio/refstudio/pull/37 for what I've implemented for prettier.

**Comment by gjreda** [comment]
@cguedes should be good now

**Review by cguedes — APPROVED** [review]
Great thanks!

**Pull request merged**
