### PR TITLE
feat: Prepare Release 23.2.0

### PR DESCRIPTION
**Pull request by cguedes**
This a release PR for [23.2.0](#540). Let's list all the tasks and issues we find during tests.

## Releases
- [`23.2.0-rc.6`](https://github.com/refstudio/refstudio/releases/tag/untagged-9cea3f305ee1c861fc07)
- [`23.2.0-rc.5`](https://github.com/refstudio/refstudio/releases/tag/untagged-3f0a788927206860f4b1)
- [`23.2.0-rc.4`](https://github.com/refstudio/refstudio/releases/tag/untagged-873e09302c7c776a968e)
- [`23.2.0-rc.3`](https://github.com/refstudio/refstudio/releases/tag/untagged-144aca62655261a6318b) 
- [`23.2.0-rc.2`](https://github.com/refstudio/refstudio/releases/tag/untagged-4c04e6f08f4345534ffe) 
- [`23.2.0-rc.1`](https://github.com/refstudio/refstudio/releases/tag/untagged-a427d5c1665966f53969) 

## Tasks

- [x] [Create releases](https://github.com/refstudio/refstudio/actions/workflows/cut-release.yml) for team tests (@cguedes) 
- [x] Confirm the app runs in Apple Intel Chip (@cguedes)
- [x] Confirm the app runs in Apple Silicon Chip (@cguedes)
- [x] Add release instructions to README.md (@cguedes)
- [x] Update README.md with new Logo (@cguedes)
- [ ] Record RefStudio demo video
- [ ] Update README.md with new print-screen, and video

- [x] #562
- [x] #564
- [x] #565 (fixed in 4befc31ea1bc954d5eb5db03e161e93da17f3a24)
- [x] #567 (fixed in 9eb60e57817a82f8c29a2256efb902732762f67a)
- [x] #569 
- [x] #568 (workaround in 9d7fa59e3a5178feb02094781904fb35b0af7eca by enabling logs by default)
- [x] #570 (fixed in 861e58fa608a419fa4aa085c33a9da741101ee6a)
- [x] give modal z-index to command palette (fixed in 8580b5bf1881b3640d5194dff44d50387e4a8b41)
- [x] make rewrite loading spinner small (fixed in 6cf60ad925d74a7bbc02f569ed9360ff847f3f88)

## Release
- [ ] Update package.json to 23.2.0 (@cguedes)
- [ ] Create a release for `32.2.0` using [Cut Release Action](https://github.com/refstudio/refstudio/actions/workflows/cut-release.yml) and selecting the branch `main` (@cguedes)
- [ ] Edit the [release](https://github.com/refstudio/refstudio/releases) to update description (if needed) and publish release
    - Make sure we note [this know issue](https://github.com/refstudio/refstudio/pull/560#issuecomment-1729834907)

> **Note:** Everyone can edit this description to add (adjust) items.

### CODE REVIEW

**Comment by cguedes** [comment]
After installing my apple silicon version, I've got [this error](https://github.com/refstudio/refstudio/pull/508#issuecomment-1717368386). Fixed by running `xattr -cr /Applications/refstudio.app`.

**Comment by jvoytek** [comment]
Saving spinner spins continuously until you type something into a new file.

**Comment by cguedes** [comment]
# Test Steps (desktop)

## First Run & Project Lifecycle
- [ ] Ensure `/tmp/web-storage-url/user1/` don't exist
- [ ] Run the application for the first time and see the welcome screen with the logo in the center
- [ ] Open the sample project and verify you can open the existing files
- [ ] Close sample project and see that the list or projects now contains the sample project
- [ ] Create a new project
- [ ] Create some files and edit their content, use shortcut; the menu action in the projects sidebar and the command palette

## Editor
- [ ] Confirm that the editor content is auto-saved
- [ ] Verify that we can edit in markdown and use other common shortcuts to make text bold and italic
- [ ] Verify we can have collapsible sections
- [ ] Verify we can move blocks around
- [ ] Verify we can enter block navigation mode by pressing ESC
- [ ] Verify we can navigate, select, and manipulate blocks

## Settings
- [ ] Open settings modal via shortcut and icon in the left sidebar
- [ ] Update the AI provider (to Ollama), adjust the Creativity Level and save
- [ ] Restart RefStudio and verify that settings were saved
- [ ] Update back to Open AI

## References
- [ ] Verify that an empty project show no references in the side panel
- [ ] Verify that the footer shows `References: 0`
- [ ] Verify that we can open references editor (table) using: click in the footer item; menu action `References -> Open`; shortcut `cmd` + `R`; icon in the references pane; and Command Palette "Open References";
- [ ] Upload references using 3 methods: sidebar button; references table button; drag-and-drop PDF files;
- [ ] Verify that footer displays "References Ingestion" loading indicator, that disappear after ingestion finish; and the references counter updated to the number of PDFs added
- [ ] Verify that ingested PDFs are listed in the project sidebar under `uploads`
- [ ] Verify that ingested references are listed in the references sidebar
- [ ] Verify that clicking on a reference open the reference details page
- [ ] Verify that we can click the pencil to edit: citation key, title, and DOI
- [ ] Verify that clicking on the PDF icon, in the reference details, will open the PDF
- [ ] Verify that ingested references are listed in the references table
- [ ] Verify that we can edit cells in the table to edit references metadata: citation key, title, published date, and authors
- [ ] Verify that we can open the reference details page, from the references table
- [ ] Verify that we can open the reference PDF, from the references table
- [ ] Open a file and type `[` to trigger the references popup with all the ingested references, select one
- [ ] Type `@` inside a citation element to trigger the references popup to add an additional reference
- [ ] Type extra text (ex: `, page 2`) inside the citation. You should have something similar to `[@domingos; @sculley, page 2]`

## Rewriter
- [ ] Open a file and select some text, then open the rewrite panel and see the "Text Selection" contains the selected text
- [ ] Open a file and select some text, then choose "Rewrite Selection...` and see that the rewrite panel opens with the "Text Selection" containing the selected text
- [ ] Confirm that the Rewriter Speech Type and Creativity Level default to the settings values
- [ ] Confirm we can adjust Speech Type and Creativity Level
- [ ] (with Open AI and an empty API Key) press Rewrite and see that an error message pop
- [ ] (with Open AI and a valid API Key) press Rewrite and see the first variation of 3 available, move between variations using `>` and `<`
- [ ] Ask for a rewrite, and press Insert to replace the selected text in the editor, or to insert at the cursor without a selection
- [ ] Ask for a rewrite and press the copy icon, observe that a popup with "Variant copied" was shown briefly. Verify that the content is in the system clipboard

## ChatBot
- [ ] Open the Chatbot clicking in the right sidebar 🤖 , then close by clicking again, and open using `cmd` + `0`
- [ ] Open the Chatbot using the command palette action `Chat with References...`
- [ ] Type a question in the text area and press ENTER
- [ ] Type a question in the text area and press Shift+ENTER to create a line break instead of asking the question
- [ ] Verify that the chat bot response is streamed, showing text in chunks

## Text Completion
- [ ] Open a file and ensure that we have some text, put the cursor in the end of a paragraph (or anywhere else) and trigger the text completion using: command palette action; shortcut `Cmd` + `J`. Verify that `...` are shown followed by the proposed text in light grey
- [ ] Cycle between proposed options using `cmd` + `K`
- [ ] Accept proposed text using TAB
- [ ] Accept proposed text using `→`

## IDE
- [ ] Trigger the command palette using `cmd` + `K`
- [ ] List files using `cmd` + `P` and open one of the files
- [ ] Verify we can show/hide side panels using drag and shortcuts (`cmd` + `1`, ...)
- [ ] Verify we can adjust panel dimensions
- [ ] Verify we can click to see notifications, and that we can clear them
- [ ] Verify we can move editors between LEFT and RIGHT pane, via context menu and via command pallete
- [ ] Verify we can close all open editors
- [ ] Verify we can view the keyboard shortcuts

## Local LLM
- [ ] Install **Ollama** with `llama2`, and test the AI features

---- 
# Example file content

> You can use this for the tests. Copy paste and adjust styles using markdown and block navigation and edit.

```md
Ref Studio

Motivation

Foundation model capabilities are rapidly improving and writing support systems are a promising early use case. Because foundation models are better at fluency than factuality, early experiments have focused on creative writing rather than expository, argumentative, or academic writing. Ref Studio will facilitate experimentation with factual writing support systems by providing an open source text editor that integrates foundation models and referenced document contents. 

Features

Ref Studio has three main components focused on writing, references, and AI interactions.

Writing

The writing component is supported by a text editor with basic styling with Markdown syntax, Notion-like blocks that can be collapsed, re-arranged, and display associated annotation widgets, such as cited references.

References

References play a crucial role in scientific document writing. Ref Studio offers a built-in feature for managing references. You have the option to upload your PDF references, which will be analyzed and made easily accessible to assist you throughout the writing process. Additionally, Ref Studio provides a dedicated system interface to efficiently manage your references.

AI Interactions

When editing documents you can ask AI assistance to rewrite parts of the text, and get answers using the chat. Additionally you can also ask for text completion in the editor.
```

**Comment by cguedes** [comment]
> Saving spinner spins continuously until you type something into a new file.

Does this happen when you open a new file (and also when you create a new project), or anywhere else?

**Comment by sehyod** [comment]
After following all steps (and doing some other tests), here are a few issues I found:

- Moving a PDF to another panel doesn't work
- ChatBot doesn't work, I get an error (Error: Expected event stream content type text/event-stream, got text/html)
- Ollama doesn't work at all, I also get an error ('async for' requires an object with __aiter__ method, got ModelResponse)

**Comment by sehyod** [comment]
Logging setting does not seem to be working properly: logging only use the env variable instead of using the config

**Comment by cguedes** [comment]
> I'm getting an error that the application is damaged when trying to open it. This if for both [refstudio_23.2.0-rc.2_aarch64.dmg](https://github.com/refstudio/refstudio/releases/download/untagged-4c04e6f08f4345534ffe/refstudio_23.2.0-rc.2_aarch64.dmg) and [refstudio_23.2.0-rc.2_aarch64-debug.dmg](https://github.com/refstudio/refstudio/releases/download/untagged-4c04e6f08f4345534ffe/refstudio_23.2.0-rc.2_aarch64-debug.dmg)
> 
> image
> EDIT: x64 is working though 🤔

This happened to me also! Check my [comment above](https://github.com/refstudio/refstudio/pull/560#issuecomment-1727933326).

We need to make this info into the release notes.

**Comment by hammer** [comment]
@cguedes so currently any Apple Silicon user is going to have to manually modify xattrs to use Ref Studio? How did we introduce this regression, and is possible to fix the build somehow?

**Comment by cguedes** [comment]
> @cguedes so currently any Apple Silicon user is going to have to manually modify xattrs to use Ref Studio? How did we introduce this regression, and is possible to fix the build somehow?

@hammer I think this only happens if you have installed the app before (maybe event the dev version). I will investigate this a bit further.

**Comment by cguedes** [comment]
> > @cguedes so currently any Apple Silicon user is going to have to manually modify xattrs to use Ref Studio? How did we introduce this regression, and is possible to fix the build somehow?
> 
> @hammer I think this only happens if you have installed the app before (maybe event the dev version). I will investigate this a bit further.

I didn't found much more about this. This [article](https://appletoolbox.com/app-is-damaged-cannot-be-opened-mac/) explains this a bit more.

**Review by sehyod — APPROVED** [review]

**Review by gjreda — APPROVED** [review]

**Comment by gjreda** [comment]
Came across this article today and dropping it here as I imagine it might be useful for our next release https://defn.io/2023/09/22/distributing-mac-apps-with-github-actions/

**Pull request merged**
